// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKWv8v2Hb5-Hl77tiXbHH_uAX8mwiwMVE',
    appId: '1:231893834616:android:e8e67e487c21caf4d2868d',
    messagingSenderId: '231893834616',
    projectId: 'fatburner---app',
    storageBucket: 'fatburner---app.firebasestorage.app',
    authDomain: 'auth.betteralt.in',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkpOpGIO-u2RrKtYjLCkb8KGJjQVM3uSc',
    appId: '1:231893834616:ios:963ffc76f4b33b89d2868d',
    messagingSenderId: '231893834616',
    projectId: 'fatburner---app',
    storageBucket: 'fatburner---app.firebasestorage.app',
    iosBundleId: 'in.betteralt.app',
    iosClientId: '231893834616-4v6jtvgssji3dsimeu1lltjpeo5pcg21.apps.googleusercontent.com',
  );
}
